# Continuous integration tasks running on Cirrus CI.
#

env:
  GITHUB_ACTION: 1
  WXRUBY_TEST_EXCLUDE: 'test_config:test_intl:test_media_ctrl'
  GITHUB_TOKEN: ENCRYPTED[2ce3914266dec78118dd9706c25d2e52fbd164f86713692efde9b8af5f0159099cb299934a8d6279e524da7a0790e025]

verify_task:
  skip: "changesIncludeOnly('.yardopts','*.md','.circleci/**','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb')"
  only_if: $CIRRUS_BRANCH =~ 'master'
  matrix:
    - name: Cirrus CI / Fedora AMD64
      container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / Fedora ARM64
      arm_container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / OpenSuSE Leap AMD64
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / OpenSuSE Leap ARM64
      arm_container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / Ubuntu AMD64
      container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Ubuntu ARM64
      arm_container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Debian AMD64
      container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / Debian ARM64
      arm_container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a

  build_script: |
    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

  test_script:
    /bin/bash -o pipefail -c "xvfb-run -a -s '-screen 0 1600x1200x24' bundle exec rake test"

release_task:
  only_if: $CIRRUS_RELEASE != '' || $CIRRUS_BUILD_SOURCE == 'api'
  matrix:
    - name: Cirrus CI / Fedora AMD64
      container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / Fedora ARM64
      arm_container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / OpenSuSE Leap AMD64
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / OpenSuSE Leap ARM64
      arm_container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / Ubuntu AMD64
      container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Ubuntu ARM64
      arm_container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Debian AMD64
      container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / Debian ARM64
      arm_container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a

  system_build_script: |
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

    bundle exec rake binpkg

  system_cleanup_script: |
    bundle exec rake clean
    rm -rf ext/wxWidgets
    rm -f .wxconfig
    
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh remove

  latest_build_script:
    ./tools/scripts/cirrus/setup-ruby-install-latest.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log
    
    bundle exec rake binpkg

  release_script:

    ruby tools/scripts/cirrus/upload-release-pkg.rb
