# Continuous integration tasks running on Cirrus CI.
#

env:
  GITHUB_ACTION: 1
  WXRUBY_TEST_EXCLUDE: 'test_config:test_intl:test_media_ctrl'

task:
  skip: "changesIncludeOnly('.yardopts','*.md','.circleci/**','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb')"
  only_if: $CIRRUS_BRANCH =~ 'pull/.*' || $CIRRUS_RELEASE != '' || $CIRRUS_BUILD_SOURCE == 'api'
  matrix:
    - name: Cirrus CI / Fedora AMD64
      container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / OpenSuSE Leap AMD64
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / Ubuntu AMD64
      container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Ubuntu ARM64
      arm_container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu
    - name: Cirrus CI / Debian AMD64
      container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / Debian ARM64
      arm_container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian


  before_script: |

    . tools/scripts/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a

  build_script: |
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    \curl -sSL https://get.rvm.io | bash -s head
    export PATH="$PATH:$HOME/.rvm/bin"
    . /usr/local/rvm/scripts/rvm && rvm install ruby-3.2
    . /usr/local/rvm/scripts/rvm && rvm alias create default ruby-3.2
    
    ruby -v

    bundle install
    
    bundle exec rake configure[--with-wxwin,--autoinstall]

    bundle exec rake build

  test_script:
    . /usr/local/rvm/scripts/rvm

    /bin/bash -o pipefail -c "xvfb-run -a -s '-screen 0 1600x1200x24' bundle exec rake test"

  bingem_script:
    . /usr/local/rvm/scripts/rvm

    bundle exec rake bingem
