# Continuous integration tasks running on Cirrus CI.
#

task:
  skip: "changesIncludeOnly('.yardopts','*.md','.circleci/**','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb')"
  matrix:
    - name: Cirrus CI / Fedora 39
      container:
        image: fedora:39
      env:
        osname: linux
        distro: fedora
        arch: amd64

  before_script: |

    sudo dnf install -y git xorg-x11-server-Xvfb xorg-x11-fonts-75dpi which gcc make procps-ng

    # Show some information about the system.
    uname -a
    locale
    locale -a

  build_script: |
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    \curl -sSL https://get.rvm.io | bash -s head
    export PATH="$PATH:$HOME/.rvm/bin"
    . /usr/local/rvm/scripts/rvm && rvm install ruby-3.2
    . /usr/local/rvm/scripts/rvm && rvm alias create default ruby-3.2
    
    ruby -v

    bundle install
    
    bundle exec rake configure[--with-wxwin,--autoinstall]

    bundle exec rake build

  test_script:
    . /usr/local/rvm/scripts/rvm

    /bin/bash -o pipefail -c "xvfb-run -a -s '-screen 0 1600x1200x24' bundle exec rake test"
